# Generated by Django 4.2.7 on 2026-06-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "classes",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "class_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="students.class",
                    ),
                ),
            ],
            options={
                "db_table": "sections",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20, unique=True)),
                ("roll_no", models.CharField(blank=True, max_length=10)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GEN", "General"),
                            ("OBC", "OBC"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("EWS", "EWS"),
                        ],
                        default="GEN",
                        max_length=5,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("religion", models.CharField(blank=True, max_length=50)),
                ("nationality", models.CharField(default="Indian", max_length=50)),
                ("mother_tongue", models.CharField(blank=True, max_length=50)),
                ("aadhar_no", models.CharField(blank=True, max_length=12)),
                ("session_year", models.CharField(max_length=10)),
                ("father_name", models.CharField(max_length=100)),
                ("father_phone", models.CharField(max_length=15)),
                ("father_occupation", models.CharField(blank=True, max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("mother_phone", models.CharField(blank=True, max_length=15)),
                ("guardian_name", models.CharField(blank=True, max_length=100)),
                ("guardian_phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("tc_issued", "TC Issued"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("admission_date", models.DateField()),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("using_transport", models.BooleanField(default=False)),
                ("using_hostel", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.section",
                    ),
                ),
                (
                    "sibling",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siblings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["class_ref__order", "section__name", "first_name"],
            },
        ),
    ]
