# Generated by Django 4.2.7 on 2026-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_subjectallocation'),
        ('staff', '0007_alter_staff_class_assigned_and_more'),
        ('students', '0003_sectionmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_year', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_master',
                'ordering': ['-session_year'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='class_ref',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'ordering': ['-admission_date']},
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
