# Generated by Django 4.2.7 on 2026-06-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sessionmaster_remove_section_class_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsectionmaster',
            options={'managed': False, 'ordering': ['class_master', 'section_master']},
        ),
    ]
