# Generated by Django 4.2.7 on 2026-06-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorisedPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("relation", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("id_proof_type", models.CharField(blank=True, max_length=50)),
                ("id_proof_no", models.CharField(blank=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="authorised_persons/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "authorised_persons",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feedback", "Feedback"),
                            ("suggestion", "Suggestion"),
                            ("complaint", "Complaint"),
                        ],
                        default="feedback",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feedbacks",
            },
        ),
        migrations.CreateModel(
            name="HRMLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.IntegerField()),
                ("staff_name", models.CharField(max_length=200)),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("confirmation", "Confirmation"),
                            ("increment", "Increment"),
                            ("warning", "Warning"),
                            ("termination", "Termination"),
                            ("experience", "Experience"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date", models.DateField()),
                ("issued_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hrm_letters",
            },
        ),
        migrations.CreateModel(
            name="ShortLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("class_name", models.CharField(max_length=50)),
                ("section_name", models.CharField(max_length=10)),
                ("reason", models.TextField()),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField(blank=True, null=True)),
                ("leave_date", models.DateField()),
                ("authorized_by", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "short_leaves",
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("enquiry", "Enquiry"),
                            ("delivery", "Delivery"),
                            ("other", "Other"),
                        ],
                        default="meeting",
                        max_length=20,
                    ),
                ),
                ("whom_to_meet", models.CharField(max_length=100)),
                ("id_proof_type", models.CharField(blank=True, max_length=50)),
                ("id_proof_no", models.CharField(blank=True, max_length=50)),
                ("visit_date", models.DateField(auto_now_add=True)),
                ("in_time", models.TimeField(auto_now_add=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "db_table": "visitors",
                "ordering": ["-visit_date", "-in_time"],
            },
        ),
    ]
