# Generated by Django 4.2.7 on 2026-06-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timetable", "0001_initial"),
        ("staff", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("passing_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "weightage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("session_year", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "exam_types",
            },
        ),
        migrations.CreateModel(
            name="RemarkMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "remark_masters",
            },
        ),
        migrations.CreateModel(
            name="SignatureMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("signature", models.ImageField(upload_to="signatures/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "signature_masters",
            },
        ),
        migrations.CreateModel(
            name="SubjectAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_year", models.CharField(max_length=10)),
                (
                    "class_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.class"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "subject_allocations",
                "unique_together": {
                    ("class_ref", "section", "subject", "session_year")
                },
            },
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_year", models.CharField(max_length=10)),
                ("is_elective", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "db_table": "student_subjects",
                "unique_together": {("student", "subject", "session_year")},
            },
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                            ("D", "D"),
                            ("E1", "E1"),
                            ("E2", "E2"),
                        ],
                        max_length=3,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("is_absent", models.BooleanField(default=False)),
                ("entered_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.examtype",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "db_table": "marks",
                "unique_together": {("student", "subject", "exam_type")},
            },
        ),
    ]
