# Generated by Django 6.0.6 on 2026-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remark', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'grade_scales',
                'ordering': ['-min_percent'],
            },
        ),
    ]
