# Generated by Django 4.2.7 on 2026-06-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_gradescale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectAllocation',
        ),
    ]
