# Generated by Django 4.2.7 on 2026-06-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetable_section_timetable_sections'),
        ('students', '0004_sessionmaster_remove_section_class_ref_and_more'),
        ('academics', '0003_delete_subjectallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(max_length=20)),
                ('min_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('grade_type', models.CharField(choices=[('marks_based', 'Marks Based'), ('direct', 'Direct Grade')], default='marks_based', max_length=12)),
                ('session_year', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'grade_master',
                'ordering': ['grade_type', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_mode', models.CharField(choices=[('marks', 'Marks'), ('marks_grade', 'Marks Based Grade'), ('direct', 'Direct Grade')], default='marks', max_length=12)),
                ('session_year', models.CharField(max_length=10)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classmaster')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsectionmaster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
            ],
            options={
                'db_table': 'subject_assignments',
                'unique_together': {('class_ref', 'section', 'subject', 'session_year')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('session_year', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTestMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_marks', to='academics.subjectassignment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.test')),
            ],
            options={
                'db_table': 'subject_test_marks',
                'unique_together': {('assignment', 'test')},
            },
        ),
    ]
