# Generated by Django 4.2.7 on 2026-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_subject_session'),
        ('students', '0004_sessionmaster_remove_section_class_ref_and_more'),
        ('academics', '0004_grade_subjectassignment_test_subjecttestmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoScholasticSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'co_scholastic_subjects',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='session_year',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='subjectassignment',
            old_name='session_year',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='session_year',
            new_name='session',
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('class_ref', 'section', 'subject', 'session')},
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='is_co_scholastic',
            field=models.BooleanField(default=False),
        ),
    ]
