# Generated by Django 4.2.7 on 2026-06-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sessionmaster_remove_section_class_ref_and_more'),
        ('academics', '0005_coscholasticsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoScholasticAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=10)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classmaster')),
                ('co_scholastic_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.coscholasticsubject')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsectionmaster')),
            ],
            options={
                'db_table': 'co_scholastic_assignments',
                'unique_together': {('co_scholastic_subject', 'class_ref', 'section', 'session')},
            },
        ),
    ]
