# Generated by Django 4.2.7 on 2026-06-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sessionmaster_remove_section_class_ref_and_more'),
        ('timetable', '0005_subject_session'),
        ('academics', '0006_coscholasticassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='class_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classmaster'),
        ),
        migrations.AddField(
            model_name='marks',
            name='co_scholastic_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.coscholasticsubject'),
        ),
        migrations.AddField(
            model_name='marks',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classsectionmaster'),
        ),
        migrations.AddField(
            model_name='marks',
            name='session',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='marks',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.test'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.examtype'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
    ]
