# Generated by Django 4.2.7 on 2026-06-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_classsectionmaster_options'),
        ('academics', '0007_marks_class_ref_marks_co_scholastic_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('session', models.CharField(max_length=10)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='students.classmaster')),
            ],
            options={
                'db_table': 'remarks',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RemarkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.remark')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsectionmaster')),
            ],
            options={
                'db_table': 'remark_sections',
                'unique_together': {('remark', 'section')},
            },
        ),
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=10)),
                ('entered_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classmaster')),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.remark')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classsectionmaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to='students.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.test')),
            ],
            options={
                'db_table': 'student_remarks',
                'unique_together': {('student', 'test', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='RemarkMaster',
        ),
    ]
