# Generated by Django 4.2.7 on 2026-06-20 19:28

from django.db import migrations, models


def backfill_section_ids(apps, schema_editor):
    """Collapse each Remark's RemarkSection rows into the new comma-separated
    section_ids column before the join table is dropped."""
    Remark = apps.get_model('academics', 'Remark')
    RemarkSection = apps.get_model('academics', 'RemarkSection')
    db = schema_editor.connection.alias
    for remark in Remark.objects.using(db).all():
        ids = list(
            RemarkSection.objects.using(db).filter(remark=remark).values_list('section_id', flat=True)
        )
        remark.section_ids = ','.join(str(i) for i in ids)
        remark.save(using=db)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remark_remarksection_studentremark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='section_ids',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_section_ids, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='RemarkSection',
        ),
    ]
