# Generated by Django 4.2.7 on 2026-06-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "routes",
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("drop_time", models.TimeField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "db_table": "stops",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.CharField(max_length=20, unique=True)),
                ("registration_no", models.CharField(max_length=20, unique=True)),
                ("capacity", models.IntegerField(default=40)),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_phone", models.CharField(max_length=15)),
                ("conductor_name", models.CharField(blank=True, max_length=100)),
                ("conductor_phone", models.CharField(blank=True, max_length=15)),
                ("fitness_expiry", models.DateField(blank=True, null=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "In Maintenance"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="VehicleMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "vehicle_makes",
            },
        ),
        migrations.CreateModel(
            name="VehiclePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("last_replaced", models.DateField(blank=True, null=True)),
                ("next_replacement", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="transport.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_parts",
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="transport.vehiclemake",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_models",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_make",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transport.vehiclemake",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transport.vehiclemodel",
            ),
        ),
        migrations.CreateModel(
            name="StudentTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("session_year", models.CharField(max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="transport.stop"
                    ),
                ),
            ],
            options={
                "db_table": "student_transport",
            },
        ),
        migrations.AddField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transport.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="TransportAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("morning", "Morning"), ("evening", "Evening")],
                        default="morning",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        default="present",
                        max_length=10,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "db_table": "transport_attendance",
                "unique_together": {("student_id", "date", "trip_type")},
            },
        ),
    ]
