# Generated by Django 4.2.7 on 2026-06-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='Class')),
                ('status', models.BooleanField(default=True, help_text='1=Active, 0=Inactive')),
                ('session', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class_master',
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=10, verbose_name='Section')),
                ('status', models.BooleanField(default=True, help_text='1=Active, 0=Inactive')),
                ('session', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='masters.classmaster')),
            ],
            options={
                'db_table': 'class_section_master',
                'ordering': ['class_master', 'section_name'],
            },
        ),
    ]
