# Generated by Django 4.2.7 on 2026-06-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_sectionmaster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsectionmaster',
            unique_together={('class_master', 'section_name', 'session')},
        ),
    ]
