# Generated by Django 4.2.7 on 2026-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_classsectionmaster_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('father_mobile', models.CharField(max_length=15)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('tc_issued', 'TC Issued')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-admission_date'],
            },
        ),
    ]
