# Generated by Django 4.2.7 on 2026-06-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_student'),
    ]

    operations = [
        # Drop the old students table if it exists with wrong schema
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS students CASCADE;',
            reverse_sql='SELECT 1;',  # No reverse
        ),
        # Recreate the students table with correct schema
        migrations.RunSQL(
            sql='''
                CREATE TABLE students (
                    id BIGSERIAL PRIMARY KEY,
                    admission_no VARCHAR(20) UNIQUE NOT NULL,
                    student_name VARCHAR(200) NOT NULL,
                    father_name VARCHAR(200) NOT NULL,
                    mother_name VARCHAR(200) NOT NULL,
                    date_of_birth DATE NOT NULL,
                    gender VARCHAR(1) NOT NULL,
                    father_mobile VARCHAR(15) NOT NULL,
                    mother_mobile VARCHAR(15) DEFAULT '',
                    father_email VARCHAR(254) DEFAULT '',
                    mother_email VARCHAR(254) DEFAULT '',
                    class_id INTEGER NOT NULL,
                    class_name VARCHAR(50) NOT NULL,
                    session VARCHAR(20) NOT NULL,
                    admission_date DATE NOT NULL,
                    status VARCHAR(20) DEFAULT 'active' NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
                );
                
                CREATE INDEX idx_students_admission_no ON students(admission_no);
                CREATE INDEX idx_students_class_id ON students(class_id);
                CREATE INDEX idx_students_session ON students(session);
            ''',
            reverse_sql='DROP TABLE IF EXISTS students CASCADE;',
        ),
    ]
