# Generated by Django 4.2.7 on 2026-06-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("applying_for_class", models.CharField(max_length=50)),
                ("session_year", models.CharField(max_length=10)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("applied", "Applied"),
                            ("admitted", "Admitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="enquiry",
                        max_length=10,
                    ),
                ),
                ("admission_no", models.CharField(blank=True, max_length=20)),
                ("enquiry_date", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "db_table": "new_admissions",
            },
        ),
        migrations.CreateModel(
            name="PromotionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("from_class", models.CharField(max_length=50)),
                ("from_section", models.CharField(max_length=10)),
                ("to_class", models.CharField(max_length=50)),
                ("to_section", models.CharField(max_length=10)),
                ("from_session", models.CharField(max_length=10)),
                ("to_session", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("promoted", "Promoted"),
                            ("demoted", "Demoted"),
                            ("detained", "Detained"),
                        ],
                        default="promoted",
                        max_length=15,
                    ),
                ),
                ("promoted_at", models.DateTimeField(auto_now_add=True)),
                ("promoted_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "promotion_records",
            },
        ),
        migrations.CreateModel(
            name="EnquiryFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_date", models.DateField()),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("remarks", models.TextField()),
                ("done_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="students.newadmission",
                    ),
                ),
            ],
            options={
                "db_table": "enquiry_follow_ups",
            },
        ),
    ]
