# Generated by Django 4.2.7 on 2026-06-10 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("session_year", models.CharField(max_length=10)),
                ("class_id", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "additional_fees",
            },
        ),
        migrations.CreateModel(
            name="BookSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("class_id", models.IntegerField()),
                ("class_name", models.CharField(max_length=50)),
                ("session_year", models.CharField(max_length=10)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "book_sets",
            },
        ),
        migrations.CreateModel(
            name="DepositFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deposit_date", models.DateField()),
                ("refund_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("refunded", "Refunded"),
                        ],
                        default="paid",
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("receipt_no", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "deposit_fees",
            },
        ),
        migrations.CreateModel(
            name="DiscountHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("amount", "Amount")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "discount_heads",
            },
        ),
        migrations.CreateModel(
            name="FeeHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_optional", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fee_heads",
            },
        ),
        migrations.CreateModel(
            name="FeeReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_no", models.CharField(max_length=20, unique=True)),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("class_name", models.CharField(max_length=50)),
                ("section_name", models.CharField(max_length=10)),
                ("admission_no", models.CharField(max_length=20)),
                ("session_year", models.CharField(max_length=10)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("online", "Online/NEFT/RTGS"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("dd", "Demand Draft"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("cheque_no", models.CharField(blank=True, max_length=20)),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("transaction_id", models.CharField(blank=True, max_length=50)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "late_fine",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("bounced", "Cheque Bounced"),
                        ],
                        default="paid",
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("collected_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fee_receipts",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UniformItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unisex")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stock", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "uniform_items",
            },
        ),
        migrations.CreateModel(
            name="UniformSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_mode", models.CharField(default="cash", max_length=10)),
                ("receipt_no", models.CharField(max_length=20, unique=True)),
                ("collected_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "uniform_sales",
            },
        ),
        migrations.CreateModel(
            name="UniformSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fees.uniformsale",
                    ),
                ),
                (
                    "uniform_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fees.uniformitem",
                    ),
                ),
            ],
            options={
                "db_table": "uniform_sale_items",
            },
        ),
        migrations.CreateModel(
            name="StudentFeeDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("session_year", models.CharField(max_length=10)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("approved_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fees.discounthead",
                    ),
                ),
                (
                    "fee_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fees.feehead",
                    ),
                ),
            ],
            options={
                "db_table": "student_fee_discounts",
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.IntegerField()),
                ("class_name", models.CharField(max_length=50)),
                ("section_id", models.IntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("annually", "Annually"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=15,
                    ),
                ),
                ("session_year", models.CharField(max_length=10)),
                (
                    "due_date",
                    models.IntegerField(
                        default=10, help_text="Day of month by which fee is due"
                    ),
                ),
                (
                    "late_fine_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fee_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="fees.feehead",
                    ),
                ),
            ],
            options={
                "db_table": "fee_structures",
            },
        ),
        migrations.CreateModel(
            name="FeeReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fee_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fees.feehead"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fees.feereceipt",
                    ),
                ),
            ],
            options={
                "db_table": "fee_receipt_items",
            },
        ),
        migrations.CreateModel(
            name="BookSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_mode", models.CharField(default="cash", max_length=10)),
                ("receipt_no", models.CharField(max_length=20, unique=True)),
                ("collected_by", models.IntegerField(blank=True, null=True)),
                (
                    "book_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fees.bookset",
                    ),
                ),
            ],
            options={
                "db_table": "book_sales",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stock", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "book_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="fees.bookset",
                    ),
                ),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
