# Generated by Django 4.2.7 on 2026-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('old', 'Old'), ('new', 'New')], max_length=10)),
                ('session', models.CharField(max_length=20)),
                ('head_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('april', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('june', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('july', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('august', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('september', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('october', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('november', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('december', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('january', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('february', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('march', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fee_amount',
                'unique_together': {('class_id', 'type', 'session', 'head_name')},
            },
        ),
    ]
