# Generated by Django 4.2.7 on 2026-06-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_admissionquery'),
        ('fees', '0002_feeamount'),
    ]

    operations = [
    ]
