# Generated by Django 4.2.7 on 2026-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_add_adm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionquery',
            name='adm_status',
            field=models.CharField(default='enquiry', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionquery',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('contacted', 'Contacted'), ('visited', 'Visited'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='enquiry', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True)),
                ('student_name', models.CharField(max_length=200)),
                ('admission_no', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('fee_head_name', models.CharField(max_length=100)),
                ('april', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('june', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('july', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('august', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('september', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('october', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('november', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('december', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('january', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('february', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('march', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('april_paid', models.BooleanField(default=False)),
                ('may_paid', models.BooleanField(default=False)),
                ('june_paid', models.BooleanField(default=False)),
                ('july_paid', models.BooleanField(default=False)),
                ('august_paid', models.BooleanField(default=False)),
                ('september_paid', models.BooleanField(default=False)),
                ('october_paid', models.BooleanField(default=False)),
                ('november_paid', models.BooleanField(default=False)),
                ('december_paid', models.BooleanField(default=False)),
                ('january_paid', models.BooleanField(default=False)),
                ('february_paid', models.BooleanField(default=False)),
                ('march_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_fee_details',
                'ordering': ['student_id', 'fee_head_name'],
                'unique_together': {('student_id', 'session', 'fee_head_name')},
            },
        ),
    ]
