from django.db import migrations, models


# head6_apr..head20_mar were never captured by a migration, but the live
# student_fee_details table already has all 240 head columns (created ahead
# of models.py at some point). These AddField ops only update Django's
# migration STATE to match models.py / the live schema — no real DDL runs,
# avoiding "column already exists" while keeping future makemigrations sane.
_state_only_head_fields = [
    migrations.AddField(model_name='studentfeedetail', name='head6_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head6_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head7_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head8_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head9_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head10_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head11_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head12_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head13_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head14_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head15_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head16_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head17_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head18_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head19_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_apr', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_may', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_jun', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_jul', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_aug', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_sep', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_oct', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_nov', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_dec', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_jan', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_feb', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    migrations.AddField(model_name='studentfeedetail', name='head20_mar', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
]


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_feepaid_add_regular_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=_state_only_head_fields,
            database_operations=[],
        ),
        migrations.CreateModel(
            name='StudentFeeHeadMonthDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('head_number', models.IntegerField()),
                ('month', models.CharField(choices=[('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March')], max_length=3)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('session', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_fee_head_month_discounts',
                'unique_together': {('student_id', 'head_number', 'month', 'session')},
            },
        ),
    ]
