# Generated by Django 4.2.7 on 2026-06-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_classmaster_classsectionmaster'),
        ('timetable', '0002_alter_period_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'period__period_order']},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students.classmaster'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.period'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students.classsectionmaster'),
        ),
    ]
