# Generated by Django 4.2.7 on 2026-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_sectionmaster'),
        ('timetable', '0003_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='section',
        ),
        migrations.AddField(
            model_name='timetable',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='timetables', to='students.classsectionmaster'),
        ),
    ]
