# Generated by Django 4.2.7 on 2026-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetable_section_timetable_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
