# Generated by Django 4.2.7 on 2026-06-13 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_department_code_remove_department_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='departments',
        ),
        migrations.CreateModel(
            name='DepartmentDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_designations', to='staff.department')),
                ('designations', models.ManyToManyField(related_name='department_mappings', to='staff.designation')),
            ],
            options={
                'db_table': 'department_designations',
                'unique_together': {('department',)},
            },
        ),
    ]
