# Generated by Django 4.2.7 on 2026-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_designation_departments_departmentdesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='staff_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='father_or_husband_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='staff_documents/pan/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
