# Generated by Django 4.2.7 on 2026-06-13 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('staff', '0004_staff_aadhar_card_staff_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='students.class'),
        ),
        migrations.AddField(
            model_name='staff',
            name='section_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_teachers', to='students.section'),
        ),
    ]
