# Generated by Django 4.2.7 on 2026-06-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_class_assigned_staff_section_assigned'),
    ]

    operations = [
        # Use raw SQL to update foreign key constraints
        # class_master and class_section_master tables already exist (created by fee-backend)
        migrations.RunSQL(
            """
            ALTER TABLE staff 
            DROP CONSTRAINT IF EXISTS staff_class_assigned_id_fkey;
            
            ALTER TABLE staff 
            ADD CONSTRAINT staff_class_assigned_id_fkey 
            FOREIGN KEY (class_assigned_id) REFERENCES class_master(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
            ALTER TABLE staff 
            DROP CONSTRAINT IF EXISTS staff_class_assigned_id_fkey;
            
            ALTER TABLE staff 
            ADD CONSTRAINT staff_class_assigned_id_fkey 
            FOREIGN KEY (class_assigned_id) REFERENCES classes(id) ON DELETE SET NULL;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE staff 
            DROP CONSTRAINT IF EXISTS staff_section_assigned_id_fkey;
            
            ALTER TABLE staff 
            ADD CONSTRAINT staff_section_assigned_id_fkey 
            FOREIGN KEY (section_assigned_id) REFERENCES class_section_master(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
            ALTER TABLE staff 
            DROP CONSTRAINT IF EXISTS staff_section_assigned_id_fkey;
            
            ALTER TABLE staff 
            ADD CONSTRAINT staff_section_assigned_id_fkey 
            FOREIGN KEY (section_assigned_id) REFERENCES sections(id) ON DELETE SET NULL;
            """
        ),
    ]
