# Generated by Django 4.2.7 on 2026-06-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_sectionmaster'),
        ('staff', '0006_alter_staff_class_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='students.classmaster'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='section_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_teachers', to='students.classsectionmaster'),
        ),
    ]
